services:
  - type: web
    name: ironbrew2-bot
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: starter
    
    healthCheckPath: /health
    
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: BOT_PREFIX
        value: "!"
      - key: PORT
        value: "10000"
